name: Deploy the static file to GitHub Page

on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.BUSMAP_TOKEN }}
        publish_dir: ./public  # default: public
